# Generated by Django 5.1.2 on 2024-12-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimformation",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="电子邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="billincome",
            name="time_in",
            field=models.DateTimeField(verbose_name="时间"),
        ),
        migrations.AlterField(
            model_name="billoutcome",
            name="time_out",
            field=models.DateTimeField(verbose_name="时间"),
        ),
    ]
